/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    /**
     * https://github.com/FasterXML/jackson-module-kotlin
     */
    const val jackson_module_kotlin: String = "com.fasterxml.jackson.module:jackson-module-kotlin:" +
            Versions.jackson_module_kotlin

    /**
     * https://github.com/nhaarman/mockito-kotlin
     */
    const val mockito_kotlin: String = "com.nhaarman.mockitokotlin2:mockito-kotlin:" +
            Versions.mockito_kotlin

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
                    Versions.de_fayard_buildsrcversions_gradle_plugin

    /**
     * http://github.com/flapdoodle-oss/embedmongo.flapdoodle.de
     */
    const val de_flapdoodle_embed_mongo: String = "de.flapdoodle.embed:de.flapdoodle.embed.mongo:" +
            Versions.de_flapdoodle_embed_mongo

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_reflect: String = "org.jetbrains.kotlin:kotlin-reflect:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://projects.spring.io/spring-boot/#/spring-boot-parent/spring-boot-devtools
     */
    const val spring_boot_devtools: String = "org.springframework.boot:spring-boot-devtools:" +
            Versions.org_springframework_boot

    /**
     * https://projects.spring.io/spring-boot/#/spring-boot-parent/spring-boot-starters/spring-boot-starter-actuator
     */
    const val spring_boot_starter_actuator: String =
            "org.springframework.boot:spring-boot-starter-actuator:" + Versions.org_springframework_boot

    /**
     * https://projects.spring.io/spring-boot/#/spring-boot-parent/spring-boot-starters/spring-boot-starter-data-mongodb
     */
    const val spring_boot_starter_data_mongodb: String =
            "org.springframework.boot:spring-boot-starter-data-mongodb:" +
                    Versions.org_springframework_boot

    /**
     * https://projects.spring.io/spring-boot/#/spring-boot-parent/spring-boot-starters/spring-boot-starter-security
     */
    const val spring_boot_starter_security: String =
            "org.springframework.boot:spring-boot-starter-security:" + Versions.org_springframework_boot

    /**
     * https://projects.spring.io/spring-boot/#/spring-boot-parent/spring-boot-starters/spring-boot-starter-test
     */
    const val spring_boot_starter_test: String =
            "org.springframework.boot:spring-boot-starter-test:" + Versions.org_springframework_boot

    /**
     * https://projects.spring.io/spring-boot/#/spring-boot-parent/spring-boot-starters/spring-boot-starter-web
     */
    const val spring_boot_starter_web: String = "org.springframework.boot:spring-boot-starter-web:" +
            Versions.org_springframework_boot

    /**
     * https://projects.spring.io/spring-cloud/
     */
    const val spring_cloud_config_server: String =
            "org.springframework.cloud:spring-cloud-config-server:" + Versions.spring_cloud_config_server

    /**
     * https://projects.spring.io/spring-cloud
     */
    const val spring_cloud_starter_config: String =
            "org.springframework.cloud:spring-cloud-starter-config:" +
                    Versions.spring_cloud_starter_config

    /**
     * https://projects.spring.io/spring-cloud
     */
    const val spring_cloud_starter_gateway: String =
            "org.springframework.cloud:spring-cloud-starter-gateway:" +
                    Versions.spring_cloud_starter_gateway

    /**
     * https://projects.spring.io/spring-cloud
     */
    const val spring_cloud_starter_netflix_eureka_client: String =
            "org.springframework.cloud:spring-cloud-starter-netflix-eureka-client:" +
                    Versions.spring_cloud_starter_netflix_eureka_client

    /**
     * https://projects.spring.io/spring-cloud
     */
    const val spring_cloud_starter_netflix_eureka_server: String =
            "org.springframework.cloud:spring-cloud-starter-netflix-eureka-server:" +
                    Versions.spring_cloud_starter_netflix_eureka_server

    /**
     * https://projects.spring.io/spring-cloud
     */
    const val spring_cloud_starter_oauth2: String =
            "org.springframework.cloud:spring-cloud-starter-oauth2:" +
                    Versions.spring_cloud_starter_oauth2

    /**
     * https://projects.spring.io/spring-cloud
     */
    const val spring_cloud_starter_openfeign: String =
            "org.springframework.cloud:spring-cloud-starter-openfeign:" +
                    Versions.spring_cloud_starter_openfeign

    /**
     * https://spring.io/spring-cloud
     */
    const val spring_cloud_starter_sleuth: String =
            "org.springframework.cloud:spring-cloud-starter-sleuth:" +
                    Versions.spring_cloud_starter_sleuth

    /**
     * https://spring.io/spring-security
     */
    const val spring_security_test: String = "org.springframework.security:spring-security-test:" +
            Versions.spring_security_test
}
