import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val jackson_module_kotlin: String = "2.9.9"

    const val mockito_kotlin: String = "2.2.0"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.5.0"

    const val de_flapdoodle_embed_mongo: String = "2.2.0"

    const val org_jetbrains_kotlin: String = "1.3.50"

    const val org_springframework_boot: String = "2.1.8.RELEASE"

    const val spring_cloud_config_server: String = "2.1.4.RELEASE"

    const val spring_cloud_starter_config: String = "2.1.4.RELEASE"

    const val spring_cloud_starter_gateway: String = "2.1.3.RELEASE"

    const val spring_cloud_starter_netflix_eureka_client: String = "2.1.3.RELEASE"

    const val spring_cloud_starter_netflix_eureka_server: String = "2.1.3.RELEASE"

    const val spring_cloud_starter_oauth2: String = "2.1.4.RELEASE"

    const val spring_cloud_starter_openfeign: String = "2.1.3.RELEASE"

    const val spring_cloud_starter_sleuth: String = "2.1.3.RELEASE"

    const val spring_security_test: String = "5.1.6.RELEASE"

    /**
     *
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "5.6.2"

    const val gradleCurrentVersion: String = "5.6.2"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
        id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
