server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
      - id: auth-service
        uri: lb://auth-service
        predicates:
        - Path=/uaa/**

      - id: accounts-service
        uri: lb://accounts-service
        predicates:
        - Path=/accounts/**
      - id: statistics-service
        uri: lb://statistics-service
        predicates:
        - Path=/statistics/**
